version: '3'
services:
  web:
    stdin_open: true
    tty: true
    build: .
    entrypoint:  ./server-entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
    networks:
      webnet:
        ipv4_address: 172.27.0.3
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_NAME: ${POSTGRES_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16

volumes:
  postgres_data: